
  CREATE TABLE "PROCUREMENT_TYPE_LKP" 
   (	"CLIENT_ID" NUMBER, 
	"LOOKUP_VALUE_ID" NUMBER, 
	"LOOKUP_NAME" VARCHAR2(250 BYTE), 
	"LOOKUP_VALUE" VARCHAR2(250 BYTE), 
	"LOOKUP_VALUE_DESC" VARCHAR2(500 BYTE), 
	"DISPLAY_ORDER" NUMBER, 
	"END_DATE" DATE, 
	"ATTRIBUTE1" VARCHAR2(500 BYTE), 
	"ATTRIBUTE2" VARCHAR2(500 BYTE), 
	"ATTRIBUTE3" VARCHAR2(500 BYTE), 
	"ATTRIBUTE4" VARCHAR2(500 BYTE), 
	"ATTRIBUTE5" VARCHAR2(500 BYTE), 
	"ATTRIBUTE6" VARCHAR2(500 BYTE), 
	"ATTRIBUTE7" VARCHAR2(500 BYTE), 
	"ATTRIBUTE8" VARCHAR2(500 BYTE), 
	"ATTRIBUTE9" VARCHAR2(500 BYTE), 
	"ATTRIBUTE10" VARCHAR2(500 BYTE), 
	"ATTRIBUTE11" VARCHAR2(500 BYTE), 
	"ATTRIBUTE12" VARCHAR2(500 BYTE), 
	"ATTRIBUTE13" VARCHAR2(500 BYTE), 
	"ATTRIBUTE14" VARCHAR2(500 BYTE), 
	"ATTRIBUTE15" VARCHAR2(500 BYTE), 
	"CREATED_BY" VARCHAR2(30 BYTE), 
	"CREATION_DATE" DATE, 
	"LAST_UPDATED_BY" VARCHAR2(30 BYTE), 
	"LAST_UPDATE_DATE" DATE, 
	"VERSION_NUMBER" NUMBER
   ) ;
   
begin
Insert into PROCUREMENT_TYPE_LKP (CLIENT_ID,LOOKUP_VALUE_ID,LOOKUP_NAME,LOOKUP_VALUE,LOOKUP_VALUE_DESC,DISPLAY_ORDER,END_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,VERSION_NUMBER) values (1,142,'PROCUREMENT_VEHICLE','CONTRACT_SBA','Contract (SBA Awarded)',0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SYSTEM',to_date('27-11-19','DD-MM-RR'),'SYSTEM',to_date('27-11-19','DD-MM-RR'),1);
Insert into PROCUREMENT_TYPE_LKP (CLIENT_ID,LOOKUP_VALUE_ID,LOOKUP_NAME,LOOKUP_VALUE,LOOKUP_VALUE_DESC,DISPLAY_ORDER,END_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,VERSION_NUMBER) values (1,143,'PROCUREMENT_VEHICLE','CONTRACT_ASSIST_ACQ','Contract (Assisted Acquistion)',0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SYSTEM',to_date('27-11-19','DD-MM-RR'),'SYSTEM',to_date('27-11-19','DD-MM-RR'),1);
Insert into PROCUREMENT_TYPE_LKP (CLIENT_ID,LOOKUP_VALUE_ID,LOOKUP_NAME,LOOKUP_VALUE,LOOKUP_VALUE_DESC,DISPLAY_ORDER,END_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,VERSION_NUMBER) values (1,144,'PROCUREMENT_VEHICLE','IAA','Interagency Agreement',0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SYSTEM',to_date('27-11-19','DD-MM-RR'),'SYSTEM',to_date('27-11-19','DD-MM-RR'),1);
Insert into PROCUREMENT_TYPE_LKP (CLIENT_ID,LOOKUP_VALUE_ID,LOOKUP_NAME,LOOKUP_VALUE,LOOKUP_VALUE_DESC,DISPLAY_ORDER,END_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,VERSION_NUMBER) values (1,145,'PROCUREMENT_VEHICLE','PCARD','Purchase Card',0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SYSTEM',to_date('27-11-19','DD-MM-RR'),'SYSTEM',to_date('27-11-19','DD-MM-RR'),1);
Insert into PROCUREMENT_TYPE_LKP (CLIENT_ID,LOOKUP_VALUE_ID,LOOKUP_NAME,LOOKUP_VALUE,LOOKUP_VALUE_DESC,DISPLAY_ORDER,END_DATE,ATTRIBUTE1,ATTRIBUTE2,ATTRIBUTE3,ATTRIBUTE4,ATTRIBUTE5,ATTRIBUTE6,ATTRIBUTE7,ATTRIBUTE8,ATTRIBUTE9,ATTRIBUTE10,ATTRIBUTE11,ATTRIBUTE12,ATTRIBUTE13,ATTRIBUTE14,ATTRIBUTE15,CREATED_BY,CREATION_DATE,LAST_UPDATED_BY,LAST_UPDATE_DATE,VERSION_NUMBER) values (1,146,'PROCUREMENT_VEHICLE','RWA','RWAs',0,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,'SYSTEM',to_date('27-11-19','DD-MM-RR'),'SYSTEM',to_date('27-11-19','DD-MM-RR'),1);
commit;
end;
/

declare 
cursor c1 is 
select * from PROCUREMENT_TYPE_LKP;
vLookupValue number;
begin
for r in c1
loop
begin
select XXAAS_LOOKUP_VALUE_SEQ.nextval into vLookupValue from dual;
insert into XXAAS_LOOKUP_VALUES
(CLIENT_ID,
LOOKUP_VALUE_ID,
LOOKUP_NAME,
LOOKUP_VALUE,
LOOKUP_VALUE_DESC,
DISPLAY_ORDER,
END_DATE,
CREATED_BY,
CREATION_DATE,
LAST_UPDATED_BY,
LAST_UPDATE_DATE,
VERSION_NUMBER)
VALUEs
(1,
vLookupValue,
r.LOOKUP_NAME,
r.LOOKUP_VALUE,
r.LOOKUP_VALUE_DESC,
r.DISPLAY_ORDER,
r.END_DATE,
'SYSTEM',
sysdate,
'SYSTEM',
sysdate,
'1');
END;    
    END LOOP;     
END;
/

drop table PROCUREMENT_TYPE_LKP;